language: node_js
sudo: required
node_js:
  - "8"
  
cache:
  directories:
    - "node_modules"

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install software-properties-common -y -qq

install:
  - npm install
  - npm run ganache >/dev/null &

script:
  - npm run coverage && cat coverage/lcov.info | coveralls