language: node_js
sudo: required
node_js:
  - "8"
  
cache:
  directories:
    - "node_modules"

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install software-properties-common -y -qq
  - npm i -g ganache-cli truffle
  - ganache-cli &>/dev/null &

install:
  - npm install

script:
  - NODE_ENV='test' npm run test

after_script:
  - npm run coverage && cat coverage/lcov.info | coveralls
