
dist: trusty
language: node_js
node_js:
  - "8"
  
cache:
  directories:
    - "node_modules"

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install software-properties-common -y -qq
  - wget "https://dist.ipfs.io/go-ipfs/v0.4.9/go-ipfs_v0.4.9_linux-amd64.tar.gz" -O /tmp/ipfs.tar.gz
  - pushd . && cd $HOME/bin && tar -xzvf /tmp/ipfs.tar.gz && popd
  - export PATH="$HOME/bin/go-ipfs:$PATH"
  - ipfs init
  - ipfs daemon &
  - npm i -g ganache-cli truffle
  - ganache-cli &>/dev/null &

install:
  - npm install

script:
  - NODE_ENV='test' npm run test